name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Portfolio.Api

    - name: Build .NET project
      run: dotnet build --no-restore
      working-directory: ./Portfolio.Api

    - name: Test .NET project
      run: dotnet test
      working-directory: ./Portfolio.Api

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install Angular dependencies
      run: npm install
      working-directory: ./Portfolio.App

    - name: Build Angular project
      run: npm run build -- --configuration production
      working-directory: ./Portfolio.App

    - name: Test Angular project
      run: npm test -- --watch=false --browsers=ChromeHeadless
      working-directory: ./Portfolio.App
